### ISSUE TITLE
Unable to link Guide properly using register function

### ISSUE THREAD

**Issue by connor-odoherty** [irobayna/stupidedi#108]
I am attempting to build a custom guide and functional group to support eAPIS/EDIFACT. As I understand it, these are the only two locations I really need to build to create a new config. I see from the documentation [here](https://github.com/kputnam/stupidedi/blob/be2a448400b0442a0c2e78fc711e7528334b0362/doc/Generating.md) that I can link a specific layout to values set in the envelope. In this case, register knows to use GS08, ST03,  GS01, and ST01 as the identifying elements. However, it is not clear from the documentation where you initialized these as the identifying elements. 

Ideally, I would like to use a value in the BGM (beginning of message segment) as the indicator of which layout to use. Could you advise on how to proceed?

**Comment by connor-odoherty** [comment]
I've built a basic interchange, functional group, and guide for PAXLST, but I can't seem to get the config to list anything beyond ```[InstructionTable(
    1: Instruction[ISA](pop: 0, drop: 0, push: TransmissionState))]```

I define my config using:

```ruby
    config.interchange.register("PAXLST") do
      Stupidedi::Versions::Interchanges::PAXLST::InterchangeDef
    end
```

But I can't see any rules beyond what I posted above. Would the value I'm passing 'PAXLST' make a difference?

**Comment by kputnam** [comment]
Hmm, I don't know much about EDIFACT but I suspect that stupidedi won't be compatible out of the box without some surgery. The reason `GS08`, `ST03`, `GS01` and `ST01` are used is because those have special meaning in X12.

I think you're saying `BuilderDsl#successors` just shows that it's waiting for an `ISA` segment. Are you trying to read from a file or generate one? There are some examples of both in the `notes` directory, or you can try reading a file with `bin/edi-pp` (after you edit it to use your configuration).

Since I'm not really familiar with EDIFACT, I'm not sure which parts are common and which are incompatible. Is the `BGM` segment like an envelope within the `ST`/`SE` envelope?

You might look in `schema/functional_group_def.rb` -- this is the `GS`/`GE` envelope instantiated in `versions/functional_groups/005010/functional_group_def.rb` (and other versions) to provide the mapping between segment names like `"ST"` to their definitions. To follow what the parser does with these, take a look at the different states in `builder/states`; for example, `FunctionalGroupState.push` is where `GS08` is used to lookup the `FunctionalGroupDef` that is referenced in the config object.

Let me know if you want to work on finding out if stupidedi can be made to work with EDIFACT and I'll be glad to chime in here and there, but I do think it might take considerable work; hard for me to say since I don't know much about EDIFACT (and it's been a while since I've worked on this project).

**Comment by kputnam** [comment]
> But I can't see any rules beyond what I posted above. Would the value I'm passing 'PAXLST' make a difference?

The value you passed to `config.interchange.register` is used to wire `ISA12` to an interchange definition. So if you pass `PAXLST`, then when the parser reads an ISA segment it looks up the twelfth element in the configuration table to kind of bootstrap itself. This happens in `InterchangeState.push` in `builder/states/interchange_state.rb`
