### ISSUE TITLE
Parsing 837D Dental Claims

### ISSUE THREAD

**Issue by hackley** [irobayna/stupidedi#114]
Hello,

I'm using stupidedi to parse some incoming medical/dental claims, put them into a sane format, and save them to a database. It's working great for Professional and Institutional claims, but I'm running into a wall with Dental. 

It looks like there's currently no guide built for dental (005010X224A2). I'm more than willing to take a stab at it, but It'd also be great if there was a quicker way to get up and running with dental claims for the time being. Is there a generic config I can use (not `hipaa`) that will allow me to navigate 005010X224A2 files until I can build out the guide for 005010X224A2?

Something like:
```ruby
config = Stupidedi::Config.generic
parser = Stupidedi::Builder::StateMachine.build(config)
```

Thanks!

**Comment by kputnam** [comment]
Hi, you can try adding an entry to a config similar to the ones for 837P in `hipaa`, but you can use the generic grammar for 837 (these are called `TransactionSetDef` instead of `Guide`).

```ruby
config = Stupidedi::Config.hipaa
config.customize do |c|
  c.transaction_set.customize do |c|
    x.register("005010X???", "HC", "837") { Stupidedi::Versions::FunctionalGroups::FiftyTen::TransactionSetDefs::HC837 }
  end
end
```

Try putting this in `bin/edi-pp` and printing an example file with `./bin/edi-pp <path-to-file>`. Since 837D hasn't been implemented, there's a chance some of the segments or elements are missing and you'll need to add definitions for them to be parsed (otherwise you'll see `InvalidSegmentVal`).

Beware that this will limit how much information the API has about the structure of the file. For instance there's probably a single NM1 loop to describe all of patients, providers, guarantors, etc, rather than each having a distinct loop. You can still access all the data, but the API has less information to help.

**Comment by hackley** [comment]
Perfect! That worked like a charm. Thanks for the help - as soon as I get some time I'm going to give defining the dental spec a try, but this is super helpful for the time being!
