### ISSUE TITLE
Stupidedi::Builder::StateMachine#read freeze

### ISSUE THREAD

**Issue by xzlstc415** [irobayna/stupidedi#129]
while I was trying to read a 837I file using the following code:

`edi_parser = Stupidedi::Builder::StateMachine.build(config)`
`parser, result = edi_parser.read(Stupidedi::Reader.build(file))`

the process hang without throwing any exception and cannot be killed by simple Ctrl+C. After investigation, I found out the issue in the 837I that causes this issue is
`HI*>M545~` 
which should be a diagnosis information but the Code List Qualifier Code is missing. so it should be
something like `HI*ABK>M545~` 

There are 23 of them in the 837I and when I manually deleted all of them the reader start to work. Is there any way to throw an exception in this case?

**Comment by kputnam** [comment]
Hi @xzlstc415, that is an interesting bug! If you can you post a minimal example 837I (with PII removed) that reproduces the problem, someone can look into it.

My guess is that because there are many different loops where `HI` can occur -- principle diagnosis, admitting diagnosis, reason for visit, cause for injury, and several more -- the parser constructs a parse tree for each possibility. If you had only one `HI` segment it would create about 10 parse trees... but the second `HI` would multiply that by 10, and the third by another 10, and so on. In your case that would probably result in 10^23 parse trees :-)

One solution would be to act more like the "strict" mode (used when you're creating X12 documents), which doesn't permit ambiguity. Depending on how that's implemented, you would either end up with a runtime exception, or a parse tree with some number of invalid segments (but the rest of the parse tree would be usable).

The other solution would be to limit the number of parse trees before throwing an exception. This seems like a good idea anyway, to prevent accidental (or intentional) DoS from runaway memory consumption like you're probably seeing here.
