### ISSUE TITLE
uninitialized constant Stupidedi::Versions::FunctionalGroups::FiftyTen::SegmentDefs::EC

### ISSUE THREAD

**Issue by bdelo** [irobayna/stupidedi#162]
I was attempting to create a 005010 834 transaction, but ran into the error `uninitialized constant Stupidedi::Versions::FunctionalGroups::FiftyTen::SegmentDefs::EC` coming from `005010/transaction_set_defs/BE834.rb:51` when adding the first `ST` segment to my builder. This is preventing us (and I would assume anyone) from using stupidedi to generate these types of files. 

I believe the reason is because the `EC` segment is not being autoloaded in `005010/segment_defs.rb`. 

version 1.3.21
ruby 2.3.7

**Comment by bdelo** [comment]
This commit I believe would fix the issue. https://github.com/irobayna/stupidedi/commit/54743fa37d8dbdbceefaac27cf68a4a233ae8a9c

I was going to create a pull request adding `:EC`. Is there any kind of timeline for a new release with this change included? Thanks

**Comment by kputnam** [comment]
We can do a release this weekend, however if you're using `837I`, there is another issue (#155) which has a fix pending. I believe it's limited to the `NM1` segments of each loop in `2300 CLAIM INFORMATION` loop.

The fix is part of a larger update, so it might take longer to make it into a release. If you're not able to wait for that release, I will push a new branch in a couple days with the correction along with other changes. You can simply copy the 837I definition from the branch without needing the other changes in the branch.

Or, if you're really in a hurry, you probably can fix it yourself. The problem is that the parentheses are incorrect, so some `NM1` segments in child loops that should be nested more deeply are accidental siblings of the `NM1`in `2300 CLAIM INFORMATION`.

Let me know if you don't mind waiting, because I'd prefer to release all the fixes together (the `EC` segment issue, and the 837I issue). Otherwise it won't be too much trouble to make a release with only the `EC` segment fix; again, the other issue will be a separate release.

**Comment by bdelo** [comment]
We're not using `837I` so I'm not really concerned with the fix for that. A quick release with just the `EC` fix would be ideal for us if possible. Thanks so much!

**Comment by irobayna** [comment]
@bdelo New version released which includes missing segment
Feel free to close issue
