### ISSUE TITLE
Schema::ComponentElementUse#id seems to be missing

### ISSUE THREAD

**Issue by natec425** [irobayna/stupidedi#185]
Hey!

it seems like `Schema::ComponentElementUse#id` is missing. If I understand correctly, it `ComponentElementUse` is a concrete class derived from `AbstractElementUse` < `AbstractUse` (which defines `id` as abstract).

Am I understanding thing correctly, or am I missing something?

Thanks so much for your time!

**Comment by kputnam** [comment]
Hi Nate, I won't have time right now to check into it, but you are probably correct. I never got around to finding a way to enforce (at definition time or in a spec) the rule that abstract methods should be implemented.

But I do have just enough time to say thanks for taking a look, it is appreciated! It's good to have someone review now and again -- some of the code is nearly a decade old, so it really just fades into the background for me! Keep submitting things as you find them, I will have more time later in the week.

**Comment by natec425** [comment]
Another similar note: `Schema::SegmentDef#required?`

I'm guessing this one would delegate to `@requirement`?

**Comment by kputnam** [comment]
Hmm, actually I don't think SegmentDef has a `@requirement`, because that information only is known when a `SegmentUse` is created. Maybe this method could throw a more descriptive error message, rather than "required? is abstract" -- like "NoMethodDef: SegmentDef doesn't have requirement inforation".

But skimming the code, I think it's rare (or doesn't happen at all) that `required?` or `optional?` is called on a `FooDef` object. The reason is the requirement value in the corresponding `FooUse` overrides whatever the definition says. For instance, a SegmentDef might say the 1st element is optional, but when the segment is actually used in a particular place, that element might be required.
