### ISSUE TITLE
Question: Is unambiguous by construction generation possible?

### ISSUE THREAD

**Issue by natec425** [irobayna/stupidedi#193]
Hi hi!

I'm trying to grok all the machinery behind building up a document so that it can be written out. It seems like there is a work being done to make sure that the AST is unambiguous. I can definitely understand why an ambiguous AST might be possible during reading, but is it possible that stupidedi could expose an API where you could directly construct an unambiguous AST?

Does this sound reasonable? I may be misunderstanding the problem, but I thought it was worth asking.

Thanks for your time!

**Comment by kputnam** [comment]
I don't think that's a useful API to have, but maybe you can tell me what the use case is? The syntax tree is more or less intermediate data structure for something getting written to a file, or for reading from a file.

Without a grammar attached to the syntax tree, there isn't a useful way to address the particular data you want to read. You *could* use the Reader to tokenize things into `SegmentTok` and treat the file as a sequence. [This](https://github.com/irobayna/stupidedi/blob/master/examples/tokenizer.rb) could be a starting point.

If you only want to spit out some X12 to a file, you could probably just take the BuilderDsl and change `method_missing` to do something else.

The syntax tree itself, LoopVal, TableVal, TransactionSetVal, etc don't really have a meaning without an associated grammar. There are other libraries that work very differently than stupidedi, where you access data as if the document was a nested "struct", and the tables, loops, segments, and elements are the fields of the "struct". In that setup, I don't think the grammar matters once the tree is constructed.

**Comment by kputnam** [comment]
Oh one thing I forgot to say, is that there is some future work planned to strip out all the ambiguous grammar support: https://github.com/irobayna/stupidedi/issues/167. But I'm not sure if that was what you meant. Currently, using BuilderDsl guarantees the syntax tree is non-ambiguous / deterministic. 

There are also recent automated tests that ensure all the grammars shipped with stupidedi are not ambigious, so they cannot parse or generate any ambiguous files: https://github.com/irobayna/stupidedi/blob/master/spec/lib/stupidedi/transaction_sets/validation/ambiguity_spec.rb

**Comment by kputnam** [comment]
Closing this issue, but if I haven't answered your question feel free to re-open.

**Comment by kputnam** [comment]
Reading this back much later, maybe what you were asking is does `BuilderDsl` prevent you from constructing and writing out a file that someone could have problems parsing due to ambiguity?

If that's the question, then yes it's prevented using the same machinery used to parse a file, but instead of building each of the possible parse trees when a choice occurs, it just throws an exception. But like I mentioned, not long from now, there won't be support for constructing multiple parse trees from the same input sequence -- whether it's input from a file or input from a programmer using `BuilderDsl`.

There are also now currently rspecs that ensure transaction set definitions aren't ambiguous so there cannot be any non-determinism when using those grammars.
