### ISSUE TITLE
How do I count the number of occurrence of a selected segment?

### ISSUE THREAD

**Issue by rdudacz** [irobayna/stupidedi#204]
I'd like to count how many times does occur the element **L11** in the provided document.

How do I do that? Is there a built-in method for it?

Thanks
```
ISA*01*0000000000*01*0000000000*ZZ*ABCDEFGHIJKLMNO*ZZ*123456789012345*101127*1719*U*00400*000003438*0*P*>
GS*SM*4405197800*999999999*20111219*1747*2100*X*004010
ST*204*0001
B2**XXXX**9999955559**PP
B2A*04
L11*NONPRIMARY*OK
MS3*XXXX*B**M
NTE**FROZEN GOODS SET TO -10d F
N1*PF*XYZ CORP*9*9995555500000
N3*31875 SOLON RD
N4*SOLON*OH*44139
N7**NONE*********FF****5300
S5*1*CL*27800*L*2444*CA*1016*E
L11*9999001947*DO
L11*9999670098*CR
L11*9999001866*DO
L11*9999669887*CR
```

**Comment by lkfken** [comment]
I don't think this is an "issue" of stupidedi.  You probably want to ask this question in places like Stackoverflow.

Anyway, to find occurrence, just use a String method <i>scan</i>

```ruby
lines = IO.read('my_edi_file.txt', 'r')
lines.scan(/L11\*/).size    # this should yield 5
```

**Comment by kputnam** [comment]
Yes, [`StateMachine#count`](https://github.com/irobayna/stupidedi/blob/master/lib/stupidedi/parser/navigation.rb#L488) should do what you want.

You'll need to be very precise about where the `L11` segments are in the document. This is because in general, the same segment can be used in different contexts (within different loops, with different qualifier elements, etc) to mean different things.

In your example, it seems there are two places `L11` can appear. Presumably they mean different things. Here's some code for illustration:

```ruby
def count(isa)
  isa.iterate(:GS) do |gs|
    gs.iterate(:ST) do |st|
      pp ["ST->L11", st.count(:L11)] #=> in your example, 1

      st.iterate(:S5) do |s5|
        pp ["ST->S5->L11", s5.count(:L11)] #=> in your example, 4
      end
    end
  end
end


cursor = parser.first
while cursor.defined?
  cursor.tap do |isa|
    count(isa)
    cursor = isa.find(:ISA)
  end
end
```

Also, in an upcoming release, you will be able to access the tokenizer directly without having to parse the document. That will make it much easier to write something like [this](https://github.com/irobayna/stupidedi/blob/gh-65/examples/tokenizer.rb#L25). On the other hand, the tokenizer is kind of low-level and doesn't know about data types, loops, tables, etc -- it's just presents a sequence of `SegmentTok` instances.

Regarding @lkfken's advice, that can work in some circumstances and fail in others. For instance, it could work if your files always have the same delimiters and the substring "L11*" never occurs where it isn't expected (like in another segment `GS*L11*0~`). But the danger is if those assumptions are wrong, you won't really know because there is no error detection.

**Comment by kputnam** [comment]
Closing this but feel free to re-open if your question wasn't answered.
