### ISSUE TITLE
Stupidedi::Exceptions::ParseError - value is too long in element B101 - where do I find definitions of elements?

### ISSUE THREAD

**Issue by rdudacz** [irobayna/stupidedi#207]
It looks like the max length of the element **B10*01** is 4 characters. Where do I find the specification of elements' length?

Is there a workaround to achieve storing longer values in the **B10*01** element than 4 characters?

**Comment by kputnam** [comment]
First lookup the definition of `B1`. From the Github project page you can press `[t]` to activate the file search. Then type in `B1` and choose the one that matches your X12 version. I think it will show `B1`'s first element is `E140`. Then you can press `[t]` again and search for `element_defs`, and choose the one that matches your X12 version.

You should probably track down the history for that definition to be certain it's a mistake. The definition in `ElementDefs` provide defaults for all uses of that element, so changing it can affect more than your use case. However, if you are very certain, it should be corrected there so that others won't be stuck with the wrong definition.

If you aren't sure, you can also create a copy of the transaction set for your own use, and make a change that extends the maximum length. Search the code base for `b::MaxLength` to see examples of this. You can put the definition in your own module namespace, then register it using `Config#customize`.

**Comment by kputnam** [comment]
Closing. Feel free to re-open if your question wasn't answered.
