### ISSUE TITLE
Value not allowed, but it should be

### ISSUE THREAD

**Issue by nickrivadeneira** [irobayna/stupidedi#208]
Hi, I'm getting a parser error:
```
Stupidedi::Exceptions::ParseError:
  value 02 is not allowed in element INS04 Maintenance Reason Code
```
However, that value should be allowed based on the following element definition. Are there other validations that might be at play here? I couldn't find anything to that effect.

https://github.com/irobayna/stupidedi/blob/373f75f11b7027d8a4a0d5f82fae4ad1c189df99/lib/stupidedi/versions/005010/element_defs.rb#L2186-L2189

**Comment by kputnam** [comment]
Yes, the element definition provides the "universe" of allowed values. But each transaction set definition can narrow that set to specific ones depending on where that segment is used.

For example, see [1](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279-HS270.rb#L160), [2](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279-HS270.rb#L377), [3](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279A1-HS270.rb#L160), [4](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279A1-HS270.rb#L377), [5](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279-HB271.rb#L179), [6](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279-HB271.rb#L488), [7](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279A1-HB271.rb#L190), [8](https://github.com/irobayna/stupidedi/blob/f4beb3dcc270a173964d2afe1b245619859acd96/lib/stupidedi/transaction_sets/005010/implementations/X279A1-HB271.rb#L499), [9](https://github.com/irobayna/stupidedi/blob/373f75f11b7027d8a4a0d5f82fae4ad1c189df99/lib/stupidedi/transaction_sets/005010/implementations/X220A1-BE834.rb#L87).

When `b::Values(...)` isn't provided as a constraint, then all values from the `ElementDef` can be given.

In some cases, the `ElementDef` doesn't specify a set of allowed values (this is due to us having incomplete knowledge of specs, not because X12 doesn't restrict values for those elements), so in that case `b::Values` would still work like you'd expect; and the absence of `b::Values` would allow any value at all, subject to min/max length etc.

**Comment by nickrivadeneira** [comment]
@kputnam Thanks for the clarification. I believe the absence of `"02"` for INS04 may be a mistake (possibly related to INS02 skipping the `"02"` value). I opened a PR to add support for it [here](https://github.com/irobayna/stupidedi/pull/209) and included a screenshot of the X12 guide as supporting evidence.

**Comment by nickrivadeneira** [comment]
Closing as this has been resolved
