### ISSUE TITLE
Generating 210 document: NoMethodError - undefined method `entry_segment_uses' for #<Stupidedi::Schema::LoopDef:0x3fd64e4d5d50 ...>

### ISSUE THREAD

**Issue by rdudacz** [irobayna/stupidedi#214]
I am trying to generate a 210 document - here's how to I am approaching it (the variable `var` is used here to keep the code clean and simple - in reality, there are data loaded from database):
```
      config = Stupidedi::Config.contrib
        b = Stupidedi::Builder::BuilderDsl.build(config)
    
        b.ISA "00", nil, "00", nil,
              "02", "#{var}",
              "#{var}", "#{var}",
              "#{isa_date}", "#{isa_time}", "U", "00401", "#{var}", "0", "#{client['isa_test_indicator']}", ">"
        b.GS "IM", "#{var}", "#{var}", "#{gs_date}", "#{gs_time}", "#{gs06_ge02}", "X", "004010"
        b.ST "210", "#{var}"
          b.B3 nil, "#{var}", "#{var}", "CC", "#{b3_date}", "#{var}", nil, "#{var}", nil, "#{var}"
          b.C3 "USD"
          b.N9 "DO", "#{var}"
          b.G62 "86", "#{g62_ship_date}"
          b.N1 "SH", "#{var}"
            b.N3 "#{var}"
            b.N4 "#{var}", "#{var}", "#{var}", "#{var}"
          b.N1 "CN", "#{var}"
            b.N3 "#{var}"
            b.N4 "#{var}", "#{var}", "#{var}", "#{var}"
          b.LX "1"
            b.L5 "1", "Linehaul Cost"
            b.L0 "1", "#{var}", "DM", "#{var}", "G", nil, nil, nil, nil, nil, "L"
            b.L1 "1", nil, nil, "#{s.shipper_linehaul_cost}"
          b.LX "2"
            b.L5 "2", "Fuel Cost"
            b.L1 "2", nil, nil, "#{var}"
          b.SPO "#{var}"
          b.L3 "#{var}", "G", nil, nil, "#{var}"
          b.SE "7", "#{var}"
        b.GE "1", "#{gs06_ge02}"
        b.IEA "1", "#{var}"
    
        b.machine.zipper.tap do |z|
          separators =
            Stupidedi::Reader::Separators.build :segment    => "~\n",
                                                :element    => "*",
                                                :component  => ":",
                                                :repetition => "^"

          w = Stupidedi::Writer::Default.new(z.root, separators)
          print w.write()
          ...
```

When I run the code, I get this error message:
```
NoMethodError - undefined method `entry_segment_uses' for #<Stupidedi::Schema::LoopDef:0x3fd64e4d5d50 ...>
Did you mean?  entry_segment_use:
```

The line of code `print w.write()` is not executed.

This is the document schema I've been provided and that should follow while creating the 210 document:
<img width="760" alt="Screen Shot 2020-02-09 at 7 15 25 PM" src="https://user-images.githubusercontent.com/3080919/74107464-a7b07080-4b70-11ea-8e01-9d07dde7e9ed.png">

What am I doing wrong and why is the error message popping up?

Thank you

**Comment by kputnam** [comment]
Sorry it's too much work to try filling in all the missing parameters to run the code and reproduce your issue, I don't have a good way to do that. Maybe you can put all the values in a hash map at the top and reference them in your example, replacing any sensitive data with dummy values and make sure you can run the code as a standalone example.

Can you paste the stacktrace so we can better see where the error occurs? Since only a `TableDef` actually has `entry_segment_uses` (plural), it seems somehow the parser is expecting to have that in some context but instead it's got a loop.

Can you paste the schema you're using or link to its file if it was included with stupidedi? It seems likely to be an issue with the schema definition but it's to hard to narrow it down yet.

**Comment by kputnam** [comment]
Since the only thing calling `entry_segment_uses` is where the parser is generating instructions on how to parse your grammar, I think it's more likely an issue with the definition of your schema. 

This happens in `AbstractState.tsequence`, which expects an array of `TableDefs` as an argument. That method is called from `TransactionSetState.instructions`, so I'm guessing you might have some segments that weren't inside a table? That seems to match the diagram you pasted, and I think that is common with third-party documentation that kind of skips some details.

Your schema should look something like this, where immediate children to the whole document are only `TableDef`. You cannot put a segment outside of a table, and maybe we're missing a sanity check to catch that error in the definition before it propagates too far.

```ruby
        HP835 = b.build("HP", "835", "Health Care Claim Payment/Advice",
          d::TableDef.header("1 - Header",
            s:: ST.use(100, ...
            s::BPR.use(200, ...
            ...

            d::LoopDef.build("1000", d::RepeatCount.bounded(200),
              s:: N1.use( 800, ...
              s:: N3.use(1000, ...
              ...,

          d::TableDef.header("2 - Details", ...
          d::TableDef.header("3 - Header", ...
```

**Comment by rdudacz** [comment]
Thank you for your reply, kputnam. Please, see below the code with data:
       ```
config = Stupidedi::Config.contrib
        b = Stupidedi::Builder::BuilderDsl.build(config)
    
        b.ISA "00", nil, "00", nil,
              "02", "TTLM",
              "ZZ", "MMLOO",
              "200210", "2114", "U", "00401", "2", "0", "P", ">"
        b.GS "IM", "TTLM", "MMLOO", "20200210", "2115", "111", "X", "004010"
        b.ST "210", "000020001"
          b.B3 nil, "A123", "A12320201", "CC", nil, "20200210", "1100", nil, "20200208", nil, "TTLM"
          b.C3 "USD"
          b.N9 "DO", "A12320201"
          b.G62 "86", "20200201"
          b.N1 "SH", "Company 1"
            b.N3 "Address 123"
            b.N4 "Los Angeles", "CA", "90013", "US"
          b.N1 "CN", "Company 2"
            b.N3 "Address 345"
            b.N4 "Las Vegas", "CA", "88901", "US"
          b.LX "1"
            b.L5 "1", "Linehaul Cost"
            b.L0 "1", "2400", "DM", "4", "G", nil, nil, nil, nil, nil, "L"
            b.L1 "1", nil, nil, "800"
          b.LX "2"
            b.L5 "2", "Fuel Cost"
            b.L1 "2", nil, nil, "150"
          b.SPO "A12320201"
          b.L3 "2400", "G", nil, nil, "950"
          b.SE "21", "000020001"
        b.GE "1", "111"
        b.IEA "1", "2"
```

I also found out that if I keep in the code only these 2 rows, it gets printed out:
```
b.ISA "00", nil, "00", nil,
              "02", "TTLM",
              "ZZ", "MMLOO",
              "200210", "2114", "U", "00401", "2", "0", "P", ">"
        b.GS "IM", "TTLM", "MMLOO", "20200210", "2115", "111", "X", "004010"
```
but if I add there this one (or anything below this row), it will throw the error mentioned above:
`b.ST "210", "#{metadata.transaction_set_nb}"`

This might be a dumb
[edi_210.pdf](https://github.com/irobayna/stupidedi/files/4182695/edi_210.pdf)
 question, but where can I get the stacktrace? In the terminal window, the whole error is literarily this:
```
Completed 500 Internal Server Error in 282ms (ActiveRecord: 15.7ms)

NoMethodError - undefined method `entry_segment_uses' for #<Stupidedi::Schema::LoopDef:0x3fd089375d04 ...>
Did you mean?  entry_segment_use:
```

That's all regarding the error, which makes it quite difficult to debug it, as I am only guessing now what element can be corrupted.

I attached the file with the instructions on how to generate the 210 document.

Also - are you suggesting that the approach I follow to generate the document is wrong? I was able to successfully generate the 990s and 214s, so I continued using this approach also for the 210.

**Comment by kputnam** [comment]
Thanks for that, I'll try to take a look tomorrow. I'm not familiar with Rails lately, but I believe there is a way to configure Rails to print backtraces of exceptions... maybe even just running it in the "test" RAILS_ENV?

See also the [Rails documentation on debugging](https://guides.rubyonrails.org/debugging_rails_applications.html). If you can't work it out, in a pinch, you can wrap your code in a `begin` .. `rescue => e; logger.error(e); end`.

**Comment by kputnam** [comment]
I'm not able to reproduce this, but your example code fails at generating the `B3` segment with the error. This makes some sense because you have `nil` for that element in the example:

```
required element B310 Date/Time Qualifier is blank at file test.rb, line 11 (Stupidedi::Exceptions::ParseError)
```

Perhaps we have unreleased code in `master`, or maybe you're using an old version and this was a bug that was fixed? Could you ensure you are using version 1.4.0 or are using `gem "stupidedi", git: "irobayna/stupidedi", branch: "master"` if using Bundler?

**Comment by rdudacz** [comment]
Hi @kputnam, thank you! The problem really was in the version of `stupidedi` I had in my Gemfile. My version was `1.2.15` and from some reason was causing problems with generating 210 files.

After upgrading to `1.4.0`, everything works fine.
