### ISSUE TITLE
Question: Is it possible to override or monkey patch validations?

### ISSUE THREAD

**Issue by kany** [irobayna/stupidedi#222]
Good afternoon,

I'm using `stupidedi-1.4.0`. My config is setup like this:

```
config = Stupidedi::Config.contrib.customize do |c|
  c.transaction_set.customize do |x|
    x.register("004010", "PO", "850") { Stupidedi::TransactionSets::FortyTen::Standards::PO850 }
  end
end
```

The `b.PO1` line looks like this, which is how the vendor requires it to be sent.

```
b.PO1 "0001", "2", "CS", "18.93", nil, nil, "3516A", nil, "ZIPTOP2"
```

When I run my test, I see this error:

```
Stupidedi::Exceptions::ParseError: for segment PO1 Baseline Item Data, elements 6 must be present when elements 7 are present
```

The next vendor might require element 6 to be present. How can I modify the validations to be unique per vendor?

Thanks,

Frank

**Comment by kputnam** [comment]
Hi Frank,

I think @irobayna may have more experience with PO-850, but to answer your question generally: the best way to go about customizing the grammar for a particular vendor is to make a copy of the definition and put it in your own namespace. In your case, you can copy the source for `Stupidedi::TransactionSets::FortyTen::Standards::PO850` and name it `MyApp::VendorABC::PO850`.

Then you would change your configuration line accordingly. You should know those parameters to `x.register` are matched to elements in the input in a one-to-one relationship. That means if you have multiple vendors that all use the same `GS01`, `GS08`, `ST03`, you will need some other way to determine which grammar to use, and then use `#configure` for that vendor's grammar.

One other thing I should mention is there are two types of grammars. The first is `TransactionSetDefs` which only list all the segments, loops, and tables. Whether an element is required or not is assumed from the definition of each segment, it's not specified by the `TransactionSetDef`.

The other kind of grammar is an implementation `Guide`, which starts where the `TransactionSetDef` leaves off. It specifies element-level details like which are required or not. It also can decrease the number of occurrences of a segment or loop, and it can remove segments and loops so long as they aren't marked required by the `TransactionSetDef`. You can think of `Guide`s as a subset of `TransactionSetDef`s because any input accepted by the former will be accepted by the ladder but not the other way around.

My suggestion is to copy an existing `Guide` for PO-850, rather than use a `TransactionSetDef`, and then make the changes you want. If there isn't already a `Guide`, you don`t have to create one from scratch -- you can start by pasting the `TransactionSetDef` and then editing. There are many examples of `Guides` and you can compare them to their corresponding `TransactionSetDef` to get an idea of what's involved in defining one.

Let me know if you have further questions and good luck!

**Comment by kany** [comment]
Thank you for your detailed response, @kputnam!
