### ISSUE TITLE
Need help for parsing a very simple piece of file

### ISSUE THREAD

**Issue by painforever** [irobayna/stupidedi#223]
I checked the doc and issues but no useful information found. I actually just need to grab the "AK9"'s first element and "IK5"'s first element as in below:

```
ISA*00*          *00*          *ZZ*INDEPEND HEALTH*ZZ*QCU            *200529*1702*^*00501*000000001*0*P*:~
TA1*000000061*200529*1653*A*000~
GS*FA*INDEPEND HEALTH*QCU*20200529*170200*1*X*005010X231A1~
ST*999*0001*005010X231A1~
AK1*HC*61*005010X222A1~
AK2*837*0061*005010X222A1~
IK5*A~
AK9*A*1*1*1~
SE*6*0001~
GE*1*1~
IEA*1*000000001~
```

I tried like 

```ruby
`require "stupidedi"
require "pp"

input = File.read("decrypted.txt")
config = Stupidedi::Config.hipaa
parser = Stupidedi::Parser::StateMachine.build(config)
parser, result = parser.read(Stupidedi::Reader.build(input))

puts parser.find(:TA1)
puts parser.find(:ISA)
```

but not working, any help please, thanks
![Screen Shot 2020-06-08 at 6 00 30 PM](https://user-images.githubusercontent.com/2458972/84084829-395eac00-a9b2-11ea-92e8-5887b8392377.png)

**Comment by painforever** [comment]
![Screen Shot 2020-06-08 at 6 00 30 PM](https://user-images.githubusercontent.com/2458972/84084743-0fa58500-a9b2-11ea-86a1-3f3b6fedc37a.png)

**Comment by kputnam** [comment]
Hi @painforever,

When you read a file, the `parser` value returned to you points to the **end** of the document (`IEA`). Calling `#find` will search for segments that occur **after** the parser location. So, it will not find anything because nothing occurs past the end of the document. The reason for this is to allow you to read more files into the same document tree by appending to the end.

You can refer to [this section section of the README](https://github.com/irobayna/stupidedi#reading-traversing) and modify it according to your needs. The important part is `parser.first` will return a cursor pointing at the beginning of the document (`ISA`). From there you can search for `TA1`. To find `AK9`, you need to first find `ST`, then `AK9`. Because `AK9` can occur multiple times, you can use `#iterate(:AK9)` to loop through all the ones within the current `ST`. It's possible for both `ISA` and `ST` to repeat too, though your trading partner may not batch up documents in that manner.

See [NAVIGATING.md](https://github.com/irobayna/stupidedi/blob/master/doc/Navigating.md) for more details. I think Github does not render the images, so you can also view it at [rubydoc.info](https://rubydoc.info/github/kputnam/stupidedi/master/file/doc/Navigating.md)

**Comment by kputnam** [comment]
Forgot to mention, `IK5` is located within an `AK2` loop, which is located within an `ST`. You can see these groupings from [the grammar](https://github.com/irobayna/stupidedi/blob/master/lib/stupidedi/transaction_sets/005010/standards/FA999.rb) or by using `edi-pp` on your input file.
