### ISSUE TITLE
Duplicate Keys

### ISSUE THREAD

**Issue by tomk-ja** [irobayna/stupidedi#238]
Getting a number of warnings during rspec runs over duplicate key defnitions...

```
versions/005010/element_defs.rb:240: warning: key "DQ" is duplicated and overwritten on line 242
versions/005010/element_defs.rb:258: warning: key "GD" is duplicated and overwritten on line 264
versions/005010/element_defs.rb:319: warning: key "RW" is duplicated and overwritten on line 337
versions/005010/element_defs.rb:322: warning: key "S4" is duplicated and overwritten on line 338
```

**Comment by kputnam** [comment]
Hi, thanks for reporting this. These are harmless and won't affect the operation of a program. I believe they are only used for generating error messages. I will gladly accept a PR that removes the duplicate key/value pairs, though.

**Comment by jsp** [comment]
I started to give it a shot but couldn't find it in code; turns out this issue was addressed with PR https://github.com/irobayna/stupidedi/pull/236

**Comment by kputnam** [comment]
Thanks @jsp for looking into that.

@tomk-ja, We don't have a release planned, since the only code changes in master is the small PR that @jsp mentioned, which fixes these warnings. If you're using Bundler you could point it to the latest commit in the repo like `gem "stupidedi", git: "https://github.com/irobayna/stupidedi.git", ref: "cca3ebdd"`. in any case, the warnings are harmless, albeit annoying.
