### ISSUE TITLE
Fails on valid file

### ISSUE THREAD

**Issue by gisborne** [irobayna/stupidedi#83]
Doing this:

input = File.open("file.x12",  :encoding => "ISO-8859-1")
config = Stupidedi::Config.default
p, result = parser.read(Stupidedi::Reader.build(input))

Fails on this believed-good input:
ISA_00_          _00_          _ZZ_PANALPINA      _02_ANOC           _160503_2119_U_00401_000000001_0_T_
GS_SM_PANALPINA_ANOC_20160503_2119_1_X_004010
ST_204_000000001
B2**ANOC**715658442-01**PP
B2A_00
L11_PALA_SCA
L11_TPE540871_HB
L11_69539112301_MB
G62_11_20160430
AT5_DEL
NTE**DISPATCHER: Diane Johnson, Diane.Johnson@panalpina.com
S5_1_LD_218.00_L_1_PC
G62_69_20160430_U_0800
G62_69_20160430_K_1000
NTE**SL8D# 8296498DOCK HIGH TRUCK NEEDED
N1_SF_EVA AIRWAYS
N3_BLDG.151 JFK AIRPORT
N4_Jamaica_NY_11430
G61_IC_ISF PAYS THRU EPIC_TE_718-2445500
L5_1_WAFERSTEPPER COMPONENT  LT ME ADJ. TOOL SET  Q'TY:
S5_2_UL_218.00_L_1_PC
G62_70_20160430_X_1400
N1_ST_ASML C/O DB SCHENKER
N3_6 OLD STONE BREAK ROAD hrs:7day_/week 0700-1900,dock high 50lbs
N4_Ballston Spa_NY_12020
G61_IC_Receiving_TE_518-256-9197
L3_218.00*G********_1_L
SE_26_000000001
GE_1_1
IEA_1_000000001

**Comment by kputnam** [comment]
Hi Guyren,

It looks like your example has an incomplete `ISA` segment. The last element `ISA16` should be the component separator, which is a single-character delimiter. Usually this is In your example, this character at the end of the `ISA` is missing, so the parser skips to the next line and reads `G` as the next character.

I'm not sure exactly what message you see, but I hoped it would be an error. When in run `edi-pp`, it just prints the `ISA` segment without any other messages, so somehow it discarded the rest of the input. I'm not sure what the reason is, but the simple solution is to fix the `ISA` segment by putting a delimiter like `:` at the end of it.

Side note: your `ISA` also does not have a segment delimiter, which is usually `~`. This is normally the last character of the segment. I think this works because the parser reads `\n` as the delimiter, which is consistent with the rest of your example, and I actually think this is valid and handled this way intentionally, but I mention it because it's unusual. Normally the delimiter is `~` and characters like `\n` are discarded by the parser, but in this case I think it's used as a delimiter.

**Comment by kputnam** [comment]
@gisborne Were you able to figure this one out? It seemed to be a problem with your input (though I'm not sure what error you saw), but if you don't think that is the case let me know and include more details so I can troubleshoot.
